//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "clients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revenda_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub document: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub zip_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub street: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub complement: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub neighborhood: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub document_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub legal_rep_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub legal_rep_document: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub legal_rep_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub legal_rep_phone: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::companies::Entity")]
    Companies,
    #[sea_orm(
        belongs_to = "super::revendas::Entity",
        from = "Column::RevendaId",
        to = "super::revendas::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Revendas,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::revendas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Revendas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
