//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "companies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revenda_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub subdomain: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_domain: Option<String>,
    pub active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub demo_end_date: Option<DateTime>,
    pub demo_start_date: Option<DateTime>,
    pub is_demo_mode: bool,
    pub billing_day: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub complement: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub document: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub document_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub monthly_fee: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub neighborhood: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub payment_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub segment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub street: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub trade_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub zip_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tax_regime: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub accountant_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub accountant_email: Option<String>,
    pub opening_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opening_hours: Option<String>,
    pub active_modules: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub contract_number: Option<String>,
    pub contract_start_date: Option<DateTime>,
    pub contract_end_date: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub contract_status: Option<String>,
    pub auto_renewal: Option<bool>,
    pub notice_period_days: Option<i32>,
    pub signed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub signed_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub billing_status: Option<String>,
    pub last_billing_date: Option<DateTime>,
    pub next_billing_date: Option<DateTime>,
    pub billing_suspended_at: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub late_fee_percent: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub interest_percent: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gateway_customer_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_payment_method_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub payment_provider: Option<String>,
    pub issue_invoice: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_observations: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cnae: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub municipal_tax_regime: Option<String>,
    pub simple_national_option: Option<bool>,
    pub simple_national_since: Option<DateTime>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tax_incentives: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub nfse_settings: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub nfe_settings: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cte_settings: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub nfce_settings: Option<Json>,
    pub max_users: Option<i32>,
    pub max_branches: Option<i32>,
    pub max_invoices_per_month: Option<i32>,
    pub storage_limit_mb: Option<i32>,
    pub current_storage_usage_mb: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub blocked_reason: Option<String>,
    pub blocked_at: Option<DateTime>,
    pub last_access_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_login_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub schema_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub db_connection_string: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timezone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    #[sea_orm(column_name = "dateFormat", column_type = "Text", nullable)]
    pub date_format: Option<String>,
    #[sea_orm(column_name = "numberFormat", column_type = "Text", nullable)]
    pub number_format: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub currency: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_warehouse_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_price_table_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub support_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub support_phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preferred_contact_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub internal_tags: Option<Vec<String>>,
    pub lgpd_accepted_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lgpd_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub data_retention_policy: Option<String>,
    pub two_factor_required: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_policy_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state_registration: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub municipal_registration: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub sped_settings: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_company_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub owner_user_id: Option<String>,
    pub systems: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Clients,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCompanyId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::company_systems::Entity")]
    CompanySystems,
    #[sea_orm(has_many = "super::contracts::Entity")]
    Contracts,
    #[sea_orm(
        belongs_to = "super::revendas::Entity",
        from = "Column::RevendaId",
        to = "super::revendas::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Revendas,
    #[sea_orm(has_many = "super::tickets::Entity")]
    Tickets,
    #[sea_orm(has_many = "super::user_companies::Entity")]
    UserCompanies,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::company_systems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanySystems.def()
    }
}

impl Related<super::contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contracts.def()
    }
}

impl Related<super::revendas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Revendas.def()
    }
}

impl Related<super::tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tickets.def()
    }
}

impl Related<super::user_companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCompanies.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
