//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contracts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revenda_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub company_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub start_date: DateTime,
    pub end_date: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub amount: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub terms: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyId",
        to = "super::companies::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Companies,
    #[sea_orm(
        belongs_to = "super::revendas::Entity",
        from = "Column::RevendaId",
        to = "super::revendas::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Revendas,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::revendas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Revendas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
