//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod access_rules;
pub mod blog_posts;
pub mod clients;
pub mod companies;
pub mod company_systems;
pub mod contact_requests;
pub mod contracts;
pub mod erp_instances;
pub mod logs;
pub mod revenda_systems;
pub mod revendas;
pub mod sea_orm_active_enums;
pub mod sessions;
pub mod suggestions;
pub mod ticket_actions;
pub mod ticket_assignments;
pub mod tickets;
pub mod user_companies;
pub mod users;
