//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::access_rules::Entity as AccessRules;
pub use super::blog_posts::Entity as BlogPosts;
pub use super::clients::Entity as Clients;
pub use super::companies::Entity as Companies;
pub use super::company_systems::Entity as CompanySystems;
pub use super::contact_requests::Entity as ContactRequests;
pub use super::contracts::Entity as Contracts;
pub use super::erp_instances::Entity as ErpInstances;
pub use super::logs::Entity as Logs;
pub use super::revenda_systems::Entity as RevendaSystems;
pub use super::revendas::Entity as Revendas;
pub use super::sessions::Entity as Sessions;
pub use super::suggestions::Entity as Suggestions;
pub use super::ticket_actions::Entity as TicketActions;
pub use super::ticket_assignments::Entity as TicketAssignments;
pub use super::tickets::Entity as Tickets;
pub use super::user_companies::Entity as UserCompanies;
pub use super::users::Entity as Users;
