//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "revendas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub domain: Option<String>,
    pub active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub complement: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub document: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub document_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub neighborhood: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub street: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub zip_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::clients::Entity")]
    Clients,
    #[sea_orm(has_many = "super::companies::Entity")]
    Companies,
    #[sea_orm(has_many = "super::contracts::Entity")]
    Contracts,
    #[sea_orm(has_many = "super::erp_instances::Entity")]
    ErpInstances,
    #[sea_orm(has_many = "super::revenda_systems::Entity")]
    RevendaSystems,
    #[sea_orm(has_many = "super::tickets::Entity")]
    Tickets,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contracts.def()
    }
}

impl Related<super::erp_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErpInstances.def()
    }
}

impl Related<super::revenda_systems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RevendaSystems.def()
    }
}

impl Related<super::tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tickets.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
