//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TicketPriority")]
pub enum TicketPriority {
    #[sea_orm(string_value = "BAIXA")]
    Baixa,
    #[sea_orm(string_value = "MEDIA")]
    Media,
    #[sea_orm(string_value = "ALTA")]
    Alta,
    #[sea_orm(string_value = "URGENTE")]
    Urgente,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TicketStatus")]
pub enum TicketStatus {
    #[sea_orm(string_value = "AGUARDANDO_ATENDIMENTO")]
    AguardandoAtendimento,
    #[sea_orm(string_value = "AGENDADO")]
    Agendado,
    #[sea_orm(string_value = "EM_EXECUCAO")]
    EmExecucao,
    #[sea_orm(string_value = "IMPLANTACAO")]
    Implantacao,
    #[sea_orm(string_value = "CONCLUIDO")]
    Concluido,
    #[sea_orm(string_value = "CANCELADO")]
    Cancelado,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "UserType")]
pub enum UserType {
    #[sea_orm(string_value = "CODESDEVS_SUPERADMIN")]
    CodesdevsSuperadmin,
    #[sea_orm(string_value = "CODESDEVS_SUPORTE")]
    CodesdevsSuporte,
    #[sea_orm(string_value = "REVENDA_ADMIN")]
    RevendaAdmin,
    #[sea_orm(string_value = "REVENDA_SUPORTE")]
    RevendaSuporte,
    #[sea_orm(string_value = "REVENDA_GERENTE")]
    RevendaGerente,
    #[sea_orm(string_value = "REVENDA_CONTADOR")]
    RevendaContador,
    #[sea_orm(string_value = "CLIENTE_ADMIN")]
    ClienteAdmin,
    #[sea_orm(string_value = "CLIENTE_GERENTE")]
    ClienteGerente,
    #[sea_orm(string_value = "CLIENTE_FUNCIONARIO")]
    ClienteFuncionario,
    #[sea_orm(string_value = "CLIENTE_CONTADOR")]
    ClienteContador,
}
