//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TicketPriority")]
pub enum TicketPriority {
    #[sea_orm(string_value = "BAIXA")]
    Baixa,
    #[sea_orm(string_value = "MEDIA")]
    Media,
    #[sea_orm(string_value = "ALTA")]
    Alta,
    #[sea_orm(string_value = "URGENTE")]
    Urgente,
}

impl std::fmt::Display for TicketPriority {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Baixa => write!(f, "BAIXA"),
            Self::Media => write!(f, "MEDIA"),
            Self::Alta => write!(f, "ALTA"),
            Self::Urgente => write!(f, "URGENTE"),
        }
    }
}

impl std::str::FromStr for TicketPriority {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "BAIXA" => Ok(Self::Baixa),
            "MEDIA" => Ok(Self::Media),
            "ALTA" => Ok(Self::Alta),
            "URGENTE" => Ok(Self::Urgente),
            _ => Err(format!("Invalid ticket priority: {}", s)),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TicketStatus")]
pub enum TicketStatus {
    #[sea_orm(string_value = "AGUARDANDO_ATENDIMENTO")]
    AguardandoAtendimento,
    #[sea_orm(string_value = "AGENDADO")]
    Agendado,
    #[sea_orm(string_value = "EM_EXECUCAO")]
    EmExecucao,
    #[sea_orm(string_value = "IMPLANTACAO")]
    Implantacao,
    #[sea_orm(string_value = "CONCLUIDO")]
    Concluido,
    #[sea_orm(string_value = "CANCELADO")]
    Cancelado,
}

impl std::fmt::Display for TicketStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AguardandoAtendimento => write!(f, "AGUARDANDO_ATENDIMENTO"),
            Self::Agendado => write!(f, "AGENDADO"),
            Self::EmExecucao => write!(f, "EM_EXECUCAO"),
            Self::Implantacao => write!(f, "IMPLANTACAO"),
            Self::Concluido => write!(f, "CONCLUIDO"),
            Self::Cancelado => write!(f, "CANCELADO"),
        }
    }
}

impl std::str::FromStr for TicketStatus {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AGUARDANDO_ATENDIMENTO" => Ok(Self::AguardandoAtendimento),
            "AGENDADO" => Ok(Self::Agendado),
            "EM_EXECUCAO" => Ok(Self::EmExecucao),
            "IMPLANTACAO" => Ok(Self::Implantacao),
            "CONCLUIDO" => Ok(Self::Concluido),
            "CANCELADO" => Ok(Self::Cancelado),
            _ => Err(format!("Invalid ticket status: {}", s)),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "UserType")]
pub enum UserType {
    #[sea_orm(string_value = "CODESDEVS_SUPERADMIN")]
    CodesdevsSuperadmin,
    #[sea_orm(string_value = "CODESDEVS_SUPORTE")]
    CodesdevsSuporte,
    #[sea_orm(string_value = "REVENDA_ADMIN")]
    RevendaAdmin,
    #[sea_orm(string_value = "REVENDA_SUPORTE")]
    RevendaSuporte,
    #[sea_orm(string_value = "REVENDA_GERENTE")]
    RevendaGerente,
    #[sea_orm(string_value = "REVENDA_CONTADOR")]
    RevendaContador,
    #[sea_orm(string_value = "CLIENTE_ADMIN")]
    ClienteAdmin,
    #[sea_orm(string_value = "CLIENTE_GERENTE")]
    ClienteGerente,
    #[sea_orm(string_value = "CLIENTE_FUNCIONARIO")]
    ClienteFuncionario,
    #[sea_orm(string_value = "CLIENTE_CONTADOR")]
    ClienteContador,
}
