//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::TicketPriority;
use super::sea_orm_active_enums::TicketStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tickets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub revenda_id: String,
    #[sea_orm(column_type = "Text")]
    pub company_id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub status: TicketStatus,
    pub priority: TicketPriority,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_by_id: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub closed_at: Option<DateTime>,
    pub scheduled_for: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyId",
        to = "super::companies::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Companies,
    #[sea_orm(
        belongs_to = "super::revendas::Entity",
        from = "Column::RevendaId",
        to = "super::revendas::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Revendas,
    #[sea_orm(has_many = "super::ticket_actions::Entity")]
    TicketActions,
    #[sea_orm(has_many = "super::ticket_assignments::Entity")]
    TicketAssignments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::revendas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Revendas.def()
    }
}

impl Related<super::ticket_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketActions.def()
    }
}

impl Related<super::ticket_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketAssignments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
