//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::UserType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revenda_id: Option<String>,
    pub active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub must_change_password: bool,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub cpf: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub current_company_id: Option<String>,
    pub user_type: UserType,
    #[sea_orm(column_type = "Text", nullable)]
    pub hashed_refresh_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_factor_secret: Option<String>,
    pub is_two_factor_enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::companies::Entity")]
    Companies,
    #[sea_orm(has_many = "super::logs::Entity")]
    Logs,
    #[sea_orm(
        belongs_to = "super::revendas::Entity",
        from = "Column::RevendaId",
        to = "super::revendas::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Revendas,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::suggestions::Entity")]
    Suggestions,
    #[sea_orm(has_many = "super::ticket_actions::Entity")]
    TicketActions,
    #[sea_orm(has_many = "super::ticket_assignments::Entity")]
    TicketAssignments,
    #[sea_orm(has_many = "super::tickets::Entity")]
    Tickets,
    #[sea_orm(has_many = "super::user_companies::Entity")]
    UserCompanies,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Logs.def()
    }
}

impl Related<super::revendas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Revendas.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::suggestions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suggestions.def()
    }
}

impl Related<super::ticket_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketActions.def()
    }
}

impl Related<super::ticket_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketAssignments.def()
    }
}

impl Related<super::tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tickets.def()
    }
}

impl Related<super::user_companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCompanies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
