use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "CDS Hub API",
        version = "0.1.0",
        description = "API central do ecossistema CDS — autenticação, gestão de usuários, empresas, clientes e integração com ecossistemas parceiros."
    ),
    paths(
        crate::auth::routes::login,
        crate::auth::routes::verify_2fa,
        crate::auth::routes::refresh_token,
        crate::auth::routes::logout,
        crate::auth::routes::switch_company,
        crate::auth::routes::companies_context,
        crate::auth::routes::list_sessions,
        crate::auth::routes::revoke_session,
        crate::auth::routes::revoke_all_sessions,
        crate::auth::routes::generate_2fa,
        crate::auth::routes::turn_on_2fa,
        crate::auth::routes::turn_off_2fa,
        crate::auth::routes::change_password,
        crate::users::routes::create_user,
        crate::users::routes::list_users,
        crate::users::routes::get_user,
        crate::users::routes::update_user,
        crate::companies::routes::create_company,
        crate::companies::routes::list_companies,
        crate::companies::routes::get_company,
        crate::companies::routes::update_company,
        crate::companies::routes::delete_company,
        crate::clients::routes::create_client,
        crate::clients::routes::list_clients,
        crate::clients::routes::get_client,
        crate::clients::routes::update_client,
        crate::clients::routes::delete_client,
        crate::revendas::routes::create_revenda,
        crate::revendas::routes::list_revendas,
        crate::revendas::routes::get_revenda,
        crate::revendas::routes::update_revenda,
        crate::revendas::routes::delete_revenda,
        crate::systems::routes::list_master_systems,
        crate::systems::routes::assign_to_revenda,
        crate::systems::routes::unassign_from_revenda,
        crate::systems::routes::find_by_revenda,
        crate::systems::routes::toggle_for_company,
        crate::systems::routes::find_by_company,
        crate::suggestions::routes::list_suggestions,
        crate::suggestions::routes::create_suggestion,
        crate::suggestions::routes::vote_suggestion,
        crate::suggestions::routes::update_suggestion_status,
    ),
    components(schemas(
        crate::auth::model::LoginRequest,
        crate::auth::model::Verify2FARequest,
        crate::auth::model::SwitchCompanyRequest,
        crate::auth::model::ChangePasswordRequest,
        crate::auth::model::TwoFAVerifyRequest,
        crate::users::model::CreateUserRequest,
        crate::users::model::UpdateUserRequest,
        crate::users::model::UserResponse,
        crate::users::model::CreateUserResponse,
        crate::common::types::UserType,
        crate::companies::model::CreateCompanyRequest,
        crate::companies::model::UpdateCompanyRequest,
        crate::companies::model::Company,
        crate::clients::model::CreateClientRequest,
        crate::clients::model::UpdateClientRequest,
        crate::clients::model::Client,
        crate::revendas::model::CreateRevendaRequest,
        crate::revendas::model::UpdateRevendaRequest,
        crate::revendas::model::Revenda,
        crate::revendas::model::RevendaSystem,
        crate::systems::model::SystemInfo,
        crate::suggestions::model::CreateSuggestionRequest,
        crate::suggestions::model::UpdateSuggestionStatusRequest,
        crate::suggestions::model::SuggestionResponse,
        crate::suggestions::model::SuggestionStatus,
        crate::suggestions::model::PaginatedSuggestions,
        crate::suggestions::model::PaginationMeta,
    )),
    tags(
        (name = "Auth", description = "Autenticação e sessões"),
        (name = "Users", description = "Gestão de usuários"),
        (name = "Companies", description = "Gestão de empresas"),
        (name = "Clients", description = "Gestão de clientes"),
        (name = "Revendas", description = "Gestão de revendas"),
        (name = "Systems", description = "Gestão de sistemas"),
        (name = "Suggestions", description = "Sugestões e votação")
    )
)]
pub struct ApiDoc;
